version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: auth_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: AuthDB
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: auth_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - auth_network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  auth_network:
    driver: bridge

volumes:
  mysql_data: